gex: 0.3.3 -> 0.3.8
Add missing inputs for

error: failed to run custom build command for `openssl-sys v0.9.75`
error: failed to run custom build command for `libgit2-sys v0.14.0+1.5.0`